global:
  scrape_interval:     5s
  evaluation_interval: 5s
  
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['identity-service:8080', 'question-service:8080', 'response-service:8080', 'score-service:8080']